export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const UPDATE_MESSAGE_IND = "UPDATE_MESSAGE_IND";

export const ADD_ROOM = "ADD_ROOM";
export const ADD_ROOMS = "ADD_ROOMS";
export const SET_INITIAL_MESSAGES = "SET_INITIAL_MESSAGES";

export const CHANGE_ACTIVE_ROOM = "CHANGE_ACTIVE_ROOM";

export const SET_USER = "SET_USER";
